version: '3'

volumes:
  db-storage:
    driver: local

services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${KANBANDATA_DB_USER}
      - POSTGRES_PASSWORD=${KANBANDATA_DB_PASSWORD}
      - POSTGRES_DB=${KANBANDATA_DB_DB}
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"      
    volumes: 
      - db-storage:/var/lib/postgresql/data    

  data:
    container_name: data
    build: 
      context: kanban-data/.
    restart: always
    environment:
      - FRONTEND_URL=${KANBANFRONT_URL}
    ports:
      - 8000:8000
    expose:
      - 8000:8000      
    depends_on:
      - db
    links:
      - db:db

  frontend:
    container_name: frontend
    build: 
      context: kanban-frontend/.
    restart: always
    environment:
      - BACK4APP_URL=${BACK4APP_URL}
      - BACK4APP_APPID=${BACK4APP_APPID}
      - BACK4APP_RESTAPIKEY=${BACK4APP_RESTAPIKEY}
      - KANBANDATA_URL=${KANBANDATA_URL}
    ports:
      - 3000:3000
    depends_on:
      - data
    links:
      - data:data