
version: '3.1'

volumes:
  db:
    driver: local


services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanbanpass
      - POSTGRES_DB=kanban
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data            